//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.chriszou.piggetup;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import android.widget.TimePicker;
import com.chriszou.piggetup.R.id;
import com.chriszou.piggetup.R.layout;

public final class AlarmConfigureActivity_
    extends AlarmConfigureActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.alarm_configure);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mAlarmTimeView = ((TextView) findViewById(id.alarm_time));
        mAlarmTimePicker = ((TimePicker) findViewById(id.timePicker1));
        {
            View view = findViewById(id.alarm_configure_remove);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AlarmConfigureActivity_.this.removeAlarm();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.alarm_configure_set);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AlarmConfigureActivity_.this.setAlarm();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.alarm_configure_close);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AlarmConfigureActivity_.this.close();
                    }

                }
                );
            }
        }
        initViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static AlarmConfigureActivity_.IntentBuilder_ intent(Context context) {
        return new AlarmConfigureActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AlarmConfigureActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AlarmConfigureActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
